//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioSulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria_Terminado_Detalle
    {
        public int IdAuditoriaTerminadoDetalle { get; set; }
        public int IdAuditoria { get; set; }
        public int IdOrigen { get; set; }
        public int IdPosicion { get; set; }
        public int IdOperacion { get; set; }
        public int IdDefecto { get; set; }
        public bool Revisado { get; set; }
        public bool Compostura { get; set; }
        public string Aud_Imagen { get; set; }
    
        public virtual Auditoria Auditoria { get; set; }
        public virtual C_Modulos C_Modulos { get; set; }
    }
}
