
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RioSulAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Auditoria
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Auditoria()
    {

        this.Auditoria_Confeccion_Detalle = new HashSet<Auditoria_Confeccion_Detalle>();

        this.Auditoria_Tendido_Detalle = new HashSet<Auditoria_Tendido_Detalle>();

        this.Auditoria_Lavanderia_Detalle = new HashSet<Auditoria_Lavanderia_Detalle>();

        this.Auditoria_Proc_Esp_Detalle = new HashSet<Auditoria_Proc_Esp_Detalle>();

        this.Auditoria_Corte_Detalle = new HashSet<Auditoria_Corte_Detalle>();

    }


    public int IdAuditoria { get; set; }

    public int IdClienteRef { get; set; }

    public string OrdenTrabajo { get; set; }

    public string PO { get; set; }

    public string Tela { get; set; }

    public string Marca { get; set; }

    public string NumCortada { get; set; }

    public string Lavado { get; set; }

    public string Estilo { get; set; }

    public string Planta { get; set; }

    public string Ruta { get; set; }

    public System.DateTime FechaRegistro { get; set; }

    public int IdUsuario { get; set; }

    public Nullable<bool> Corte { get; set; }

    public Nullable<bool> Tendido { get; set; }

    public Nullable<bool> ProcesosEspeciales { get; set; }

    public Nullable<bool> Confeccion { get; set; }

    public Nullable<bool> Terminado { get; set; }

    public Nullable<bool> Lavanderia { get; set; }

    public Nullable<System.DateTime> FechaRegistroFin { get; set; }

    public Nullable<bool> Calidad { get; set; }

    public Nullable<bool> Activo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Auditoria_Confeccion_Detalle> Auditoria_Confeccion_Detalle { get; set; }

    public virtual C_Clientes C_Clientes { get; set; }

    public virtual C_Sg_Usuarios C_Sg_Usuarios { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Auditoria_Tendido_Detalle> Auditoria_Tendido_Detalle { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Auditoria_Lavanderia_Detalle> Auditoria_Lavanderia_Detalle { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Auditoria_Proc_Esp_Detalle> Auditoria_Proc_Esp_Detalle { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Auditoria_Corte_Detalle> Auditoria_Corte_Detalle { get; set; }

}

}
