//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioSulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ClientesReferencia
    {
        public int IdCliente { get; set; }
        public int IdClienteRef { get; set; }
        public string Cve_Cliente { get; set; }
        public string Nom_Cliente { get; set; }
        public string Nom_Corto { get; set; }
        public string Num_Rfc { get; set; }
        public string Dir_Cliente { get; set; }
        public string Nom_Colonia { get; set; }
        public string Num_Cp { get; set; }
        public string Num_Telefono { get; set; }
        public string Num_Fax { get; set; }
        public string Nom_Contacto { get; set; }
        public string Nom_Estatus { get; set; }
        public string Nom_Ciudad { get; set; }
        public string Nom_Estado { get; set; }
    
        public virtual C_Clientes C_Clientes { get; set; }
    }
}
