//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioSulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ClienteMarca
    {
        public int id_ClienteMarca { get; set; }
        public Nullable<int> id_Cliente { get; set; }
        public string Clave { get; set; }
        public string Descripcion { get; set; }
    }
}
