//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioSulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Operacion_Confeccion
    {
        public int ID { get; set; }
        public int IdOperacion { get; set; }
        public int IdDefecto { get; set; }
    
        public virtual C_Conf_Confeccion C_Conf_Confeccion { get; set; }
        public virtual C_Conf_Confeccion C_Conf_Confeccion1 { get; set; }
    }
}
