//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioSulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Plantas_Areas
    {
        public int IdPlantaArea { get; set; }
        public int IdPlanta { get; set; }
        public int IdArea { get; set; }
    
        public virtual C_Conf_Confeccion C_Conf_Confeccion { get; set; }
        public virtual C_Plantas_Dynamic C_Plantas_Dynamic { get; set; }
    }
}
