//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioSulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Posicion_Lavanderia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Posicion_Lavanderia()
        {
            this.C_Posicion_Lavanderia1 = new HashSet<C_Posicion_Lavanderia>();
            this.C_Posicion_Lavanderia11 = new HashSet<C_Posicion_Lavanderia>();
        }
    
        public int ID { get; set; }
        public int IdPosicion { get; set; }
        public int IdCortador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Posicion_Lavanderia> C_Posicion_Lavanderia1 { get; set; }
        public virtual C_Posicion_Lavanderia C_Posicion_Lavanderia2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Posicion_Lavanderia> C_Posicion_Lavanderia11 { get; set; }
        public virtual C_Posicion_Lavanderia C_Posicion_Lavanderia3 { get; set; }
    }
}
