//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioSulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Procesos_Especiales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Procesos_Especiales()
        {
            this.C_Operacion_ProcesosEspeciales = new HashSet<C_Operacion_ProcesosEspeciales>();
            this.C_Operacion_ProcesosEspeciales1 = new HashSet<C_Operacion_ProcesosEspeciales>();
            this.C_Posicion_ProcesosEsp = new HashSet<C_Posicion_ProcesosEsp>();
            this.C_Posicion_ProcesosEsp1 = new HashSet<C_Posicion_ProcesosEsp>();
        }
    
        public int ID { get; set; }
        public int IdSubModulo { get; set; }
        public int IdUsuario { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Observaciones { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Operacion_ProcesosEspeciales> C_Operacion_ProcesosEspeciales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Operacion_ProcesosEspeciales> C_Operacion_ProcesosEspeciales1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Posicion_ProcesosEsp> C_Posicion_ProcesosEsp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Posicion_ProcesosEsp> C_Posicion_ProcesosEsp1 { get; set; }
        public virtual C_Sg_Usuarios C_Sg_Usuarios { get; set; }
        public virtual C_SubModulos C_SubModulos { get; set; }
    }
}
