
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RioSulAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class C_Segundas
{

    public int IdSegunda { get; set; }

    public string Estilo { get; set; }

    public string Descripcion { get; set; }

    public decimal Porcentaje_Tela { get; set; }

    public decimal Porcentaje_Corte { get; set; }

    public decimal Porcentaje_Confeccion { get; set; }

    public decimal Porcentaje_Lavanderia { get; set; }

    public decimal Porcentaje_ProcesosEspeciales { get; set; }

    public decimal Porcentaje_Terminado { get; set; }

    public decimal Costo_Estilo { get; set; }

    public decimal Costo_Segunda { get; set; }

    public System.DateTime FechaRegistro { get; set; }

}

}
