//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioSulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Sg_PantallasOperaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Sg_PantallasOperaciones()
        {
            this.T_Sg_UsuariosOperaciones = new HashSet<T_Sg_UsuariosOperaciones>();
            this.T_Sg_Bitacora = new HashSet<T_Sg_Bitacora>();
        }
    
        public int ID { get; set; }
        public Nullable<int> OperacionID { get; set; }
        public Nullable<int> PantallaID { get; set; }
    
        public virtual C_Sg_Operaciones C_Sg_Operaciones { get; set; }
        public virtual T_Sg_Pantallas T_Sg_Pantallas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Sg_UsuariosOperaciones> T_Sg_UsuariosOperaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Sg_Bitacora> T_Sg_Bitacora { get; set; }
    }
}
