//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioSulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Sg_Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Sg_Usuarios()
        {
            this.Auditorias = new HashSet<Auditoria>();
            this.C_Conf_Confeccion = new HashSet<C_Conf_Confeccion>();
            this.C_CorreosElectronicos = new HashSet<C_CorreosElectronicos>();
            this.C_Cort_Cortadores = new HashSet<C_Cort_Cortadores>();
            this.C_Lavanderia = new HashSet<C_Lavanderia>();
            this.C_Procesos_Especiales = new HashSet<C_Procesos_Especiales>();
            this.C_Terminado = new HashSet<C_Terminado>();
            this.T_Sg_UsuariosOperaciones = new HashSet<T_Sg_UsuariosOperaciones>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auditoria> Auditorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Conf_Confeccion> C_Conf_Confeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CorreosElectronicos> C_CorreosElectronicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Cort_Cortadores> C_Cort_Cortadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Lavanderia> C_Lavanderia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Procesos_Especiales> C_Procesos_Especiales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Terminado> C_Terminado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Sg_UsuariosOperaciones> T_Sg_UsuariosOperaciones { get; set; }
    }
}
