//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioSulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SubModulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_SubModulos()
        {
            this.C_Conf_Confeccion = new HashSet<C_Conf_Confeccion>();
            this.C_Cort_Cortadores = new HashSet<C_Cort_Cortadores>();
            this.C_Lavanderia = new HashSet<C_Lavanderia>();
            this.C_Procesos_Especiales = new HashSet<C_Procesos_Especiales>();
            this.C_Terminado = new HashSet<C_Terminado>();
        }
    
        public int IdSubModulo { get; set; }
        public int IdModulo { get; set; }
        public string NombreSubModulo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Conf_Confeccion> C_Conf_Confeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Cort_Cortadores> C_Cort_Cortadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Lavanderia> C_Lavanderia { get; set; }
        public virtual C_Modulos C_Modulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Procesos_Especiales> C_Procesos_Especiales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Terminado> C_Terminado { get; set; }
    }
}
