//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioSulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Sg_Bitacora
    {
        public int ID { get; set; }
        public Nullable<int> OperacionPantallaID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Orden { get; set; }
    
        public virtual C_Sg_PantallasOperaciones C_Sg_PantallasOperaciones { get; set; }
    }
}
