
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RioSulAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class T_Sg_UsuariosOperaciones
{

    public int ID { get; set; }

    public Nullable<int> UsuarioID { get; set; }

    public Nullable<int> PantallaOperacionID { get; set; }

    public Nullable<bool> Activo { get; set; }



    public virtual C_Sg_PantallasOperaciones C_Sg_PantallasOperaciones { get; set; }

    public virtual C_Sg_Usuarios C_Sg_Usuarios { get; set; }

}

}
