
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RioSulAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VST_AUDITORIA_TENDIDO_DETALLE
{

    public int IdAuditoriaCorte { get; set; }

    public int IdCortador { get; set; }

    public string ClaveCortador { get; set; }

    public string NombreCortador { get; set; }

    public string Serie { get; set; }

    public string Bulto { get; set; }

    public int IdPosicion { get; set; }

    public string ClavePosicion { get; set; }

    public string NombrePosicion { get; set; }

    public int IdDefecto { get; set; }

    public string ClaveDefecto { get; set; }

    public string NombreDefecto { get; set; }

    public int IdCortado { get; set; }

    public int Descripcion { get; set; }

    public bool ToleranciaPositiva { get; set; }

    public bool ToleranciaNegativa { get; set; }

    public int Cantidad { get; set; }

    public Nullable<int> Segundas { get; set; }

    public string Nota { get; set; }

    public string Imagen { get; set; }

    public string Archivo { get; set; }

}

}
