
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RioSulAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VST_POSICION_PROCESOS_ESPECIALES
{

    public int IdPosicion { get; set; }

    public int IdCortador { get; set; }

    public string Clave { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

}

}
