
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RioSulAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VST_PERMISOS_OPERACIONES
{

    public int ID { get; set; }

    public Nullable<int> UsuarioID { get; set; }

    public Nullable<int> PantallaID { get; set; }

    public string Pantalla { get; set; }

    public string SubMenu { get; set; }

    public int OperacionID { get; set; }

    public string Operacion { get; set; }

}

}
