
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RioSulAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VST_AUDITORIA_CORTE_DETALLE
{

    public int IdAuditoriaCorte { get; set; }

    public string Serie { get; set; }

    public string Bulto { get; set; }

    public int IdTendido { get; set; }

    public string ClaveTendido { get; set; }

    public string NombreTendido { get; set; }

    public Nullable<int> TipoTendido { get; set; }

    public int IdMesa { get; set; }

    public string ClaveMesa { get; set; }

    public string NombreMesa { get; set; }

    public int IdPosicion { get; set; }

    public string ClavePosicion { get; set; }

    public string NombrePosicion { get; set; }

    public int IdDefecto { get; set; }

    public string ClaveDefecto { get; set; }

    public string NombreDefecto { get; set; }

    public int Cantidad { get; set; }

    public Nullable<int> Segundas { get; set; }

    public string Imagen { get; set; }

    public string Nota { get; set; }

    public string Archivo { get; set; }

}

}
