
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RioSulAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VST_AUDITORIA_TERMINADO_DETALLE
{

    public int ID { get; set; }

    public string Defecto { get; set; }

    public string Operacion { get; set; }

    public string Origen { get; set; }

    public string Posicion { get; set; }

    public int IdOrigen { get; set; }

    public int IdPosicion { get; set; }

    public int IdOperacion { get; set; }

    public int IdDefecto { get; set; }

    public int IdAuditoria { get; set; }

    public int IdAuditoriaTerminadoDetalle { get; set; }

    public int Cantidad { get; set; }

    public bool Revisado { get; set; }

    public bool Compostura { get; set; }

    public string Nota { get; set; }

    public string Aud_Imagen { get; set; }

    public string Archivo { get; set; }

}

}
