
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RioSulAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VST_PERMISOS
{

    public int ID { get; set; }

    public string Nombre { get; set; }

    public Nullable<bool> Activo { get; set; }

    public int PantOper_ID { get; set; }

    public Nullable<int> OperacionID { get; set; }

    public string Operacion { get; set; }

    public string Pantalla { get; set; }

    public string SubMenu { get; set; }

    public Nullable<bool> Operacion_Activo { get; set; }

    public string Ruta { get; set; }

    public Nullable<int> Pantalla_ID { get; set; }

    public int Operacion_ID { get; set; }

    public string Icon { get; set; }

    public Nullable<int> PantallaOperacionID { get; set; }

}

}
