//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioSulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_AUDITORIA_CALIDAD_DETALLE
    {
        public int IdAuditoria { get; set; }
        public int IdPosicion { get; set; }
        public int IdOperacion { get; set; }
        public int IdDefecto { get; set; }
        public int Recup { get; set; }
        public int Fin { get; set; }
        public int Criterio { get; set; }
        public Nullable<int> Id_Origen { get; set; }
        public string Aud_Imagen { get; set; }
        public string Origen { get; set; }
        public string Operacion { get; set; }
        public string Posicion { get; set; }
        public string Defecto { get; set; }
    }
}
