//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioSulAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_AUDITORIA
    {
        public int IdAuditoria { get; set; }
        public int IdClienteRef { get; set; }
        public string OrdenTrabajo { get; set; }
        public string PO { get; set; }
        public string Tela { get; set; }
        public string Marca { get; set; }
        public string NumCortada { get; set; }
        public string Lavado { get; set; }
        public string Estilo { get; set; }
        public string Planta { get; set; }
        public string Ruta { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<bool> Corte { get; set; }
        public Nullable<bool> Tendido { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> ProcesosEspeciales { get; set; }
        public Nullable<bool> Confeccion { get; set; }
        public Nullable<bool> Terminado { get; set; }
        public Nullable<bool> Lavanderia { get; set; }
        public Nullable<System.DateTime> FechaRegistroFin { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<bool> Calidad { get; set; }
    }
}
